services:
  - type: web
    name: ai-code-review-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /api/auth/login/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: LLM_PROVIDER
        value: groq
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
